// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt3xzATLkjLa9j4eLeUxkzWNIS51Uok1E',
    appId: '1:769820971745:web:3ab742b421a6a6b2035da0',
    messagingSenderId: '769820971745',
    projectId: 'bkappcrud',
    authDomain: 'bkappcrud.firebaseapp.com',
    storageBucket: 'bkappcrud.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdnIpWanXckBg4WYI3LDChMD5Rp5-l34Q',
    appId: '1:769820971745:android:56a7dfaf0934c914035da0',
    messagingSenderId: '769820971745',
    projectId: 'bkappcrud',
    storageBucket: 'bkappcrud.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBt3xzATLkjLa9j4eLeUxkzWNIS51Uok1E',
    appId: '1:769820971745:web:5e7fff572c1c21d9035da0',
    messagingSenderId: '769820971745',
    projectId: 'bkappcrud',
    authDomain: 'bkappcrud.firebaseapp.com',
    storageBucket: 'bkappcrud.firebasestorage.app',
  );
}
